
all: 4-char.mp4 7-char.mp4 11-char.mp4 13-char.mp4 37-char.mp4 53-char.mp4

4-char.mp4: generate.sh
	./generate.sh $@ 138

7-char.mp4: generate.sh
	./generate.sh $@ 228

11-char.mp4: generate.sh
	./generate.sh $@ 350

13-char.mp4: generate.sh
	./generate.sh $@ 416

37-char.mp4: generate.sh
	./generate.sh $@ 1030

53-char.mp4: generate.sh
	./generate.sh $@ 1416
